/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ApiComponent {
    }
    interface CounterComponent {
        "amount": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLApiComponentElement extends Components.ApiComponent, HTMLStencilElement {
    }
    var HTMLApiComponentElement: {
        prototype: HTMLApiComponentElement;
        new (): HTMLApiComponentElement;
    };
    interface HTMLCounterComponentElement extends Components.CounterComponent, HTMLStencilElement {
    }
    var HTMLCounterComponentElement: {
        prototype: HTMLCounterComponentElement;
        new (): HTMLCounterComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "api-component": HTMLApiComponentElement;
        "counter-component": HTMLCounterComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface ApiComponent {
    }
    interface CounterComponent {
        "amount"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "api-component": ApiComponent;
        "counter-component": CounterComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "api-component": LocalJSX.ApiComponent & JSXBase.HTMLAttributes<HTMLApiComponentElement>;
            "counter-component": LocalJSX.CounterComponent & JSXBase.HTMLAttributes<HTMLCounterComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
